<a href="https://colab.research.google.com/github/czyz-patryk/dataScienceBootcampExercises/blob/main/Copy_of_051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.21.6'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [4]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate((A, B), axis=0)

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [5]:
np.concatenate((A, B), axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [6]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

np.concatenate((data, target), axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [7]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

np.column_stack((feature1, feature2, feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [25]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A

A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print()
print(A2)
print()
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]

[[1 0 4 4]
 [3 2 3 3]
 [0 4 2 2]
 [0 1 2 3]
 [5 1 4 2]]

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [27]:
A = np.random.randint(low=0, high=2, size=(10, 6))

print(A)

print(np.count_nonzero(A))

[[0 1 0 0 0 0]
 [1 1 0 0 0 1]
 [0 0 1 1 0 1]
 [1 0 1 0 1 0]
 [0 0 1 0 1 0]
 [0 1 0 0 1 0]
 [0 0 0 1 1 0]
 [1 0 1 0 0 0]
 [0 0 0 1 0 1]
 [0 1 1 1 0 0]]
23


Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [29]:
np.count_nonzero(A, axis=1)

array([1, 3, 3, 3, 2, 2, 2, 2, 2, 3])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [32]:
np.set_printoptions(precision=4)
A = np.random.randn(10, 4)
A

array([[ 0.3195,  0.1933,  1.5961,  0.6011],
       [-0.6443,  1.356 , -0.7396, -0.6492],
       [-0.8485, -0.9362,  0.3332, -0.2579],
       [-3.4782, -0.2683, -0.5179,  0.8928],
       [-0.5633,  2.5393,  1.3968, -0.3899],
       [ 1.1496,  0.5252,  0.2335,  0.8027],
       [ 0.0541,  0.2404,  0.8234,  2.0525],
       [ 0.2512, -0.4538, -2.0292,  1.9613],
       [-0.2632,  0.5348,  1.9059,  0.2276],
       [-0.1947,  1.4197,  0.4607,  0.5861]])

### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [33]:
np.set_printoptions(precision=8, suppress=True)

A = np.array([1.2e-6, 1.7e-7])

A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [43]:
A = np.random.randn(8, 4)

np.delete(A, 2, 1)

array([[ 1.36737025,  0.95825383,  0.74798043],
       [ 1.00510216, -0.50743729, -0.09682604],
       [-0.47553054,  1.01568695,  1.25165147],
       [-0.3669732 ,  0.47239664, -0.97597981],
       [-0.01988973,  0.33364353, -1.34270656],
       [ 1.70142924,  0.08769948,  1.62076802],
       [ 0.61738981, -1.20017   , -0.22239472],
       [ 0.29730698,  0.62279983,  0.53957241]])

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [44]:
v = np.array([3, 4, -2])

np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [46]:
np.set_printoptions(edgeitems=10)

A = np.random.randint(10, size=(100, 30))

A

array([[9, 1, 0, 8, 1, 7, 8, 3, 7, 8, ..., 6, 8, 5, 9, 0, 6, 2, 4, 9, 3],
       [9, 4, 4, 5, 9, 9, 5, 7, 7, 8, ..., 1, 0, 5, 8, 2, 5, 2, 0, 4, 9],
       [3, 6, 5, 9, 6, 4, 3, 6, 6, 5, ..., 5, 4, 2, 4, 7, 1, 5, 8, 7, 7],
       [7, 6, 7, 5, 1, 1, 7, 0, 5, 5, ..., 4, 2, 5, 5, 7, 1, 0, 3, 6, 9],
       [2, 2, 4, 4, 9, 2, 8, 3, 2, 1, ..., 2, 4, 1, 3, 5, 0, 9, 3, 5, 8],
       [1, 6, 5, 1, 7, 6, 4, 4, 6, 8, ..., 7, 5, 5, 1, 0, 1, 3, 1, 0, 6],
       [7, 5, 3, 5, 2, 7, 9, 1, 4, 0, ..., 7, 9, 0, 3, 3, 6, 6, 7, 4, 6],
       [7, 8, 2, 2, 3, 4, 9, 0, 6, 8, ..., 1, 1, 6, 9, 1, 3, 1, 5, 7, 9],
       [3, 4, 3, 2, 4, 8, 7, 7, 7, 7, ..., 9, 5, 3, 1, 5, 7, 7, 6, 5, 1],
       [6, 4, 5, 9, 7, 7, 2, 6, 0, 0, ..., 8, 1, 2, 7, 0, 9, 6, 6, 0, 8],
       ...,
       [7, 5, 2, 2, 7, 4, 9, 6, 4, 7, ..., 3, 8, 1, 1, 8, 6, 6, 0, 5, 6],
       [5, 5, 1, 5, 3, 8, 0, 7, 4, 0, ..., 4, 2, 9, 9, 1, 6, 0, 5, 5, 2],
       [1, 1, 8, 4, 6, 4, 6, 3, 7, 9, ..., 2, 8, 5, 9, 2, 6, 3, 2, 7, 3],
       [0, 5, 9, 0, 4, 6, 